//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "LDAPMon" event count 1
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = f33b46f6-70e9-4d43-ab9e-d923397a5060
EXTERN_C __declspec(selectany) const GUID LDAPMonProvider = {0xf33b46f6, 0x70e9, 0x4d43, {0xab, 0x9e, 0xd9, 0x23, 0x39, 0x7a, 0x50, 0x60}};

#ifndef LDAPMonProvider_Traits
#define LDAPMonProvider_Traits NULL
#endif // LDAPMonProvider_Traits

//
// Channel
//
#define LDAPMonProvider_CHANNEL_LDAPMon 0x10
#define LDAPMonProvider_CHANNEL_LDAPMon_KEYWORD 0x8000000000000000

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR LDAPSearch = {0x1, 0x0, 0x10, 0x4, 0x0, 0x0, 0x8000000000000000};
#define LDAPSearch_value 0x1

#define MSG_LDAPSearch_EventMessage          0xB0000001L
